### ISSUE TITLE
`bash.historyFile` does it change history file location?

### ISSUE THREAD

**Issue by mobsenpai** [Lehmanator/nix-configs#46]
Hello I just want to know that does defining the bash history file location to .local/share/bash/bash_history do change the location of the file cuz I have also defined it and and clearly see that no folder under the name "bash" in .local/share has been made and the history only shows up on the current terminal session and gets wiped after closing the terminal. Is this also an issue with you or how are you doing it? cuz I can't figure out what to do.

**Comment by Lehmanator** [comment]
I use usually either zsh or nushell, so I'm not sure, but this definitely can be achieved.

There is no NixOS option `bash.historyFile`, but there is a home-manager option: `programs.bash.historyFile`.

[Here's the HM source](https://github.com/nix-community/home-manager/blob/master/modules/programs/bash.nix)

...which just sets the `$HISTFILE` environment variable.

Not sure if this creates the directory or not. If not, you can set an XDG data file in the bash directory to create it.

So in home manager, I'd set it like:

```(nix)
programs.bash.histoyFile = "${config.xdg.dataHome}/bash/bash_history";
xdg.dataFile."bash/testFile".text = "this should force the dir to be created";
```

In NixOS with HM, I'd set a session variable like this:

```(nix)
environment.sessionVariables.HISTFILE = "$XDG_DATA_HOME/bash/bash_history";
```

**Comment by mobsenpai** [comment]
Yeah I just wanted to confirm. I mean that's a good workaround but it should have created the file by default. Also using xdg will make the file read only so anyway it won't be over-written by the system so..
I am just gonna remove the option at last.
